[package]
name = "gpio_cdev_async"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
lib_uapi = { path = "../lib_uapi" }

[lints]
workspace = true
